---
- hosts: all
  become: yes
  tasks: 
  - name: install webserver(apache2) on ubuntu14
    apt: 
     name: apache2
     state: present



  - name: start the server
    service: 
     name: apache2
     state: started
     
     
     